FROM gcr.io/distroless/python3-debian13:nonroot
LABEL org.opencontainers.image.source="https://github.com/gremlinltd/docker-base"
LABEL org.opencontainers.image.description="Distroless Python 3 base image"
WORKDIR /app
