version: 2

updates:
  - package-ecosystem: docker
    directory: "/alpine"
    schedule:
      interval: weekly
      day: monday
    commit-message:
      prefix: "chore(deps):"
    labels:
      - "dependencies"

  - package-ecosystem: docker
    directory: "/ubuntu"
    schedule:
      interval: weekly
      day: monday
    commit-message:
      prefix: "chore(deps):"
    labels:
      - "dependencies"

  - package-ecosystem: docker
    directory: "/distroless-static"
    schedule:
      interval: weekly
      day: monday
    commit-message:
      prefix: "chore(deps):"
    labels:
      - "dependencies"

  - package-ecosystem: docker
    directory: "/distroless-python"
    schedule:
      interval: weekly
      day: monday
    commit-message:
      prefix: "chore(deps):"
    labels:
      - "dependencies"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
    commit-message:
      prefix: "ci(deps):"
    labels:
      - "dependencies"
      - "ci"
    open-pull-requests-limit: 5
