FROM gcr.io/distroless/static-debian13:nonroot
LABEL org.opencontainers.image.source="https://github.com/gremlinltd/docker-base"
LABEL org.opencontainers.image.description="Distroless static base image"
WORKDIR /app
